### ISSUE TITLE
Learn How to Print "Hello World" in C language.

### ISSUE THREAD

**Issue by hasibkyau** [GitHopperX/GitCamp#7]
This is the first code you will need to learn. You should develop your self learning skill. Do google and use YouTube to solve this problem.

**Comment by hasib10101** [comment]
@GitHopperX could you please check my code. 
`#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Hello world!\n");
    return 0;
}
`

**Comment by hasib10101** [comment]
This are just test comment

**Comment by hasibkyau** [comment]
you did well myself 😀

**Comment by hasibkyau** [comment]
You follow this channel 
https://www.youtube.com/watch?v=Kwye58pHhxE
